server:
  port: 8082
eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://peer1:8081/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    # 如果需要配置成高可用，必须为false
    prefer-ip-address: false
    #如果需要配置成高可用，并且server实例在同一台机器上必须配这个
    hostname: peer2