management:
  endpoints:
    web:
      exposure:
        include: '*'
#server:
#  port: 8080

#eureka:
#  client:
#    service-url:
#      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
#      defaultZone: http://localhost:8080/eureka/
#    # 是否要注册到其他Eureka Server实例
#    register-with-eureka: false
#    # 是否要从其他Eureka Server实例获取数据
#    fetch-registry: false
#  instance:
#    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
#    prefer-ip-address: true